// Auth
export const REGISTRATION_START = "REGISTRATION_START";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_FAILED = "REGISTRATION_FAILED";
export const FETCH_USER_DETAILS_START = "FETCH_USER_DETAILS_START";
export const FETCH_USER_DETAILS_SUCCESS = "FETCH_USER_DETAILS_SUCCESS";
export const FETCH_USER_DETAILS_FAILED = "FETCH_USER_DETAILS_FAILED";
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

// Post
export const FETCH_POSTS_START = "FETCH_POSTS_START";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAILED = "FETCH_POSTS_FAILED";
export const CREATE_POST_START = "CREATE_POST_SRART";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAILED = "CREATE_POST_FAILED";

//Profile
export const FETCH_USER_PROFILE_START = "FETCH_USER_PROFILE_START";
export const FETCH_USER_PROFILE_SUCCESS = "FETCH_USER_PROFILE_SUCCESS";
export const FETCH_USER_PROFILE_FAILED = "FETCH_USER_PROFILE_FAILED";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const EDIT_USER_PROFILE_START = "EDIT_USER_PROFILE_START";
export const EDIT_USER_PROFILE_SUCCESS = "EDIT_USER_PROFILE_SUCCESS";
export const EDIT_USER_PROFILE_FAILED = "EDIT_USER_PROFILE_FAILED";
export const ADD_SKILLS_START = "ADD_SKILLS_START";
export const ADD_SKILLS_SUCCESS = "ADD_SKILLS_SUCCESS";
export const ADD_SKILLS_FAILED = "ADD_SKILLS_FAILED";
export const ADD_BIO_START = "ADD_BIO_START";
export const ADD_BIO_SUCCESS = "ADD_BIO_SUCCESS";
export const ADD_BIO_FAILED = "ADD_BIO_FAILED";
export const ADD_EDUCATION_START = "ADD_EDUCATION_START";
export const ADD_EDUCATION_SUCCESS = "ADD_EDUCATION_SUCCESS";
export const ADD_EDUCATION_FAILED = "ADD_EDUCATION_FAILED";
export const ADD_EXPERIENCE_START = "ADD_EXPERIENCE_START";
export const ADD_EXPERIENCE_SUCCESS = "ADD_EXPERIENCE_SUCCESS";
export const ADD_EXPERIENCE_FAILED = "ADD_EXPERIENCE_FAILED";
export const DELETE_EXPERIENCE_START = "DELETE_EXPERIENCE_START";
export const DELETE_EXPERIENCE_SUCCESS = "DELETE_EXPERIENCE_SUCCESS";
export const DELETE_EXPERIENCE_FAILED = "DELETE_EXPERIENCE_FAILED";
export const DELETE_EDUCATION_START = "DELETE_EDUCATION_START";
export const DELETE_EDUCATION_SUCCESS = "DELETE_EDUCATION_SUCCESS";
export const DELETE_EDUCATION_FAILED = "DELETE_EDUCATION_FAILED";
