// Auth
export const REGISTRATION_START = "REGISTRATION_START";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_FAILED = "REGISTRATION_FAILED";
export const FETCH_USER_DETAILS_START = "FETCH_USER_DETAILS_START";
export const FETCH_USER_DETAILS_SUCCESS = "FETCH_USER_DETAILS_SUCCESS";
export const FETCH_USER_DETAILS_FAILED = "FETCH_USER_DETAILS_FAILED";
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

// Post
export const FETCH_POSTS_START = "FETCH_POSTS_START";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAILED = "FETCH_POSTS_FAILED";
export const FETCH_USER_POSTS_START = "FETCH_USER_POSTS_START";
export const FETCH_USER_POSTS_SUCCESS = "FETCH_USER_POSTS_SUCCESS";
export const FETCH_USER_POSTS_FAILED = "FETCH_USER_POSTS_FAILED";
export const CREATE_POST_START = "CREATE_POST_SRART";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAILED = "CREATE_POST_FAILED";
export const LIKE_POST_START = "LIKE_POST_START";
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
export const LIKE_POST_FAILED = "LIKE_POST_FAILED";
export const UNLIKE_POST_START = "UNLIKE_POST_START";
export const UNLIKE_POST_SUCCESS = "UNLIKE_POST_SUCCESS";
export const UNLIKE_POST_FAILED = "UNLIKE_POST_FAILED";

//Profile
export const FETCH_USER_PROFILE_START = "FETCH_USER_PROFILE_START";
export const FETCH_USER_PROFILE_SUCCESS = "FETCH_USER_PROFILE_SUCCESS";
export const FETCH_USER_PROFILE_FAILED = "FETCH_USER_PROFILE_FAILED";
export const FETCH_OTHER_PERSON_PROFILE_START =
  "FETCH_OTHER_PERSON_PROFILE_START";
export const FETCH_OTHER_PERSON_PROFILE_SUCCESS =
  "FETCH_OTHER_PERSON_PROFILE_SUCCESS";
export const FETCH_OTHER_PERSON_PROFILE_FAILED =
  "FETCH_OTHER_PERSON_PROFILE_FAILED";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const EDIT_USER_PROFILE_START = "EDIT_USER_PROFILE_START";
export const EDIT_USER_PROFILE_SUCCESS = "EDIT_USER_PROFILE_SUCCESS";
export const EDIT_USER_PROFILE_FAILED = "EDIT_USER_PROFILE_FAILED";
export const ADD_SKILLS_START = "ADD_SKILLS_START";
export const ADD_SKILLS_SUCCESS = "ADD_SKILLS_SUCCESS";
export const ADD_SKILLS_FAILED = "ADD_SKILLS_FAILED";
export const ADD_BIO_START = "ADD_BIO_START";
export const ADD_BIO_SUCCESS = "ADD_BIO_SUCCESS";
export const ADD_BIO_FAILED = "ADD_BIO_FAILED";
export const ADD_EDUCATION_START = "ADD_EDUCATION_START";
export const ADD_EDUCATION_SUCCESS = "ADD_EDUCATION_SUCCESS";
export const ADD_EDUCATION_FAILED = "ADD_EDUCATION_FAILED";
export const ADD_EXPERIENCE_START = "ADD_EXPERIENCE_START";
export const ADD_EXPERIENCE_SUCCESS = "ADD_EXPERIENCE_SUCCESS";
export const ADD_EXPERIENCE_FAILED = "ADD_EXPERIENCE_FAILED";
export const DELETE_EXPERIENCE_START = "DELETE_EXPERIENCE_START";
export const DELETE_EXPERIENCE_SUCCESS = "DELETE_EXPERIENCE_SUCCESS";
export const DELETE_EXPERIENCE_FAILED = "DELETE_EXPERIENCE_FAILED";
export const DELETE_EDUCATION_START = "DELETE_EDUCATION_START";
export const DELETE_EDUCATION_SUCCESS = "DELETE_EDUCATION_SUCCESS";
export const DELETE_EDUCATION_FAILED = "DELETE_EDUCATION_FAILED";

//Comments
export const COMMENT_POST_START = "COMMENT_POST_START";
export const COMMENT_POST_SUCCESS = "COMMENT_POST_SUCCESS";
export const COMMENT_POST_FAILED = "COMMENT_POST_FAILED";
export const COMMENTS_FETCH_START = "COMMENTS_FETCH_START";
export const COMMENTS_FETCH_SUCCESS = "COMMENTS_FETCH_SUCCESS";
export const COMMENTS_FETCH_FAILED = "COMMENTS_FETCH_FAILED";

//Chat
export const FETCH_CHAT_LIST_START = "FETCH_CHAT_LIST_START";
export const FETCH_CHAT_LIST_SUCCESS = "FETCH_CHAT_LIST_SUCCESS";
export const FETCH_CHAT_LIST_FAILED = "FETCH_CHAT_LIST_FAILED";
export const FETCH_CHAT_MESSAGES_START = "FETCH_CHAT_MESSAGES_START";
export const FETCH_CHAT_MESSAGES_SUCCESS = "FETCH_CHAT_MESSAGES_SUCCESS";
export const FETCH_CHAT_MESSAGES_FAILED = "FETCH_CHAT_MESSAGES_FAILED";
export const CHAT_MESSAGE_SENT = "CHAT_MESSAGE_SENT";
export const CHAT_MESSAGE_RECEIVED = "CHAT_MESSAGE_RECEIVED";
